// apps/debate-web-ext/components/ui/button.tsx
import * as React from 'react';
import { Slot } from '@radix-ui/react-slot';
import { cva, type VariantProps } from 'class-variance-authority';

import { cn } from '@/lib/utils';

const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0",
  {
    variants: {
      variant: {
        default:
          'bg-primary text-primary-foreground shadow hover:bg-primary/90',
        destructive:
          'bg-destructive text-destructive-foreground shadow-sm hover:bg-destructive/90',
        outline:
          'border border-input bg-background shadow-sm hover:bg-accent hover:text-accent-foreground',
        secondary:
          'bg-secondary text-secondary-foreground shadow-sm hover:bg-secondary/80',
        ghost: 'hover:bg-accent hover:text-accent-foreground',
        link: 'text-primary underline-offset-4 hover:underline',
      },
      size: {
        default: 'h-9 px-4 py-2',
        sm: 'h-8 rounded-md px-3 text-xs',
        lg: 'h-10 rounded-md px-8',
        icon: 'h-9 w-9',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'default',
    },
  }
);

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean;
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : 'button';
    return (
      <Comp
        className={cn(buttonVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    );
  }
);
Button.displayName = 'Button';

export { Button, buttonVariants };

// chrome-extension/src/editor/Button.svelte
<script>
  export let background = true;
  export let disabled = false;
  export let small = false;
  export let hoverShadow = false;
</script>

<button
  on:click
  on:mousedown|preventDefault={() => {}}
  class:background
  class:small
  class:hoverShadow
  {disabled}
>
  <slot />
</button>

<style>
  button {
    border: none;
    border-radius: var(--border-radius);
    cursor: pointer;
    line-height: 1;
    padding: 0.5rem;
    margin: 0;
    color: var(--text);
    height: 2rem;
    width: max-content;
    pointer-events: auto;
    display: block;
    background: none;
    font-size: 1rem;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    gap: 0.25rem;
    white-space: nowrap;
  }
  button.hoverShadow {
    transition: box-shadow var(--transition-speed);
  }
  button.small {
    padding: 0.375rem;
    height: 1.5rem;
    font-size: 0.75rem;
  }
  button[disabled] {
    pointer-events: none;
    opacity: 0.5;
  }
  button.background {
    background-color: var(--back-two);
  }
  button:hover {
    color: var(--text-strong);
  }
  button.hoverShadow:hover {
    box-shadow: var(--shadow-small);
  }
  button.background:hover {
    background-color: var(--back-two-hover);
  }
  button:active {
    background: none;
  }
  button.background:active {
    background-color: var(--back-two-active);
  }
  button:focus {
    outline: 0;
  }
</style>
