// components/ui/button.tsx
import * as React from 'react'
import { Slot } from '@radix-ui/react-slot'
import { cva, type VariantProps } from 'class-variance-authority'

import { cn } from '@/lib/utils'

const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4 shrink-0 [&_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
  {
    variants: {
      variant: {
        default: 'bg-primary text-primary-foreground hover:bg-primary/90',
        destructive:
          'bg-destructive text-white hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60',
        outline:
          'border bg-background shadow-xs hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50',
        secondary:
          'bg-secondary text-secondary-foreground hover:bg-secondary/80',
        ghost:
          'hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50',
        link: 'text-primary underline-offset-4 hover:underline',
      },
      size: {
        default: 'h-9 px-4 py-2 has-[>svg]:px-3',
        sm: 'h-8 rounded-md gap-1.5 px-3 has-[>svg]:px-2.5',
        lg: 'h-10 rounded-md px-6 has-[>svg]:px-4',
        icon: 'size-9',
        'icon-sm': 'size-8',
        'icon-lg': 'size-10',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'default',
    },
  },
)

function Button({
  className,
  variant,
  size,
  asChild = false,
  ...props
}: React.ComponentProps<'button'> &
  VariantProps<typeof buttonVariants> & {
    asChild?: boolean
  }) {
  const Comp = asChild ? Slot : 'button'

  return (
    <Comp
      data-slot="button"
      className={cn(buttonVariants({ variant, size, className }))}
      {...props as any}
    />
  )
}

export { Button, buttonVariants }

// chrome-extension/src/editor/Button.svelte
<script>
  export let background = true;
  export let disabled = false;
  export let small = false;
  export let hoverShadow = false;
</script>

<button
  on:click
  on:mousedown|preventDefault={() => {}}
  class:background
  class:small
  class:hoverShadow
  {disabled}
>
  <slot />
</button>

<style>
  button {
    border: none;
    border-radius: var(--border-radius);
    cursor: pointer;
    line-height: 1;
    padding: 0.5rem;
    margin: 0;
    color: var(--text);
    height: 2rem;
    width: max-content;
    pointer-events: auto;
    display: block;
    background: none;
    font-size: 1rem;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    gap: 0.25rem;
    white-space: nowrap;
  }
  button.hoverShadow {
    transition: box-shadow var(--transition-speed);
  }
  button.small {
    padding: 0.375rem;
    height: 1.5rem;
    font-size: 0.75rem;
  }
  button[disabled] {
    pointer-events: none;
    opacity: 0.5;
  }
  button.background {
    background-color: var(--back-two);
  }
  button:hover {
    color: var(--text-strong);
  }
  button.hoverShadow:hover {
    box-shadow: var(--shadow-small);
  }
  button.background:hover {
    background-color: var(--back-two-hover);
  }
  button:active {
    background: none;
  }
  button.background:active {
    background-color: var(--back-two-active);
  }
  button:focus {
    outline: 0;
  }
</style>
